### ISSUE TITLE
Bug in Particle and/or FourVector

### ISSUE THREAD

**Issue by s6pepaul** [JeffersonLab/PyPWA#124]
**Describe the bug**
The Particle and/or FourVector classes are showing strange behaviour. Something is mixed up in the definition of the metric. It should be (E,px,py,pz) but it is not.

**To Reproduce**
import PyPWA as pea
a = pwa.Particle(1,1.0,2.0,3.0,4.0)
print(a.e,a.x,a.y,a.z)
results in
3.0 4.0 1.0 2.0

also
a = pwa.Particle(1,1.0,2.0,3.0,4.0)
b = pwa.Particle(14,1.1,2.1,3.1,4.1)
c = a+b
results in error
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-9c91ef4a5e44> in <module>
      1 a = pwa.Particle(1,1.0,2.0,3.0,4.0)
      2 b = pwa.Particle(14,1.1,2.1,3.1,4.1)
----> 3 c = a+b
      4 # print(a.e,a.x,a.y,a.z)
      5 # print(b.e,b.x,b.y,b.z)

~/miniforge3/envs/pwa/lib/python3.8/site-packages/PyPWA/libs/vectors/four_vector.py in __add__(self, vector)
    132     def __add__(self, vector: Union["FourVector", float]) -> "FourVector":
    133         if isinstance(vector, FourVector):
--> 134             if len(vector) == len(self):
    135                 return FourVector(
    136                     self._e + vector._e, self._x + vector._x,

~/miniforge3/envs/pwa/lib/python3.8/site-packages/PyPWA/libs/vectors/four_vector.py in __len__(self)
    160 
    161     def __len__(self):
--> 162         return len(self._x)
    163 
    164     def __getitem__(

TypeError: object of type 'float' has no len()

**Expected behavior**
Output should have been 1.0 2.0 3.0 4.0 and addition should work normally.

**System Information:**
 - OS: MacOS BigSur
 - Python Version: 3.8.6
 - PyPWA Version: 3.2.0
 - Personal Machine, JLab, or other (Explain): personal

**Comment by markjonestx** [comment]
I'm working on this now. I'll have a patch available in no more than a few hours. Particle, and the rest of the vectors were originally designed to work with Numpy arrays, but were later updated to work directly with floats. I suspect this issue relates to that adjustment.

Thank you for contributing!

**Comment by markjonestx** [comment]
The head of main should fix your issues. If it doesn't just comment here and I'll reopen the issue. If you encounter any other issues feel free to open another bug report and I'll get started on it as soon as I can.
