### ISSUE TITLE
Broken Pipe Error

### ISSUE THREAD

**Issue by lmhare** [JeffersonLab/PyPWA#81]
```
Binning Complete, 1695482 events not in range.
Starting translator, for raw_events.gamp
17600000
Starting binner
Write failed: Broken pipe
```

Unsure what happened, this was supposed to be accounted for. Can you take a look? 
Thanks!

**Comment by Markjonestx** [comment]
This isn't something that we can solve directly, this issue is caused by a direct ssh connection being closed. Consider using screen or tmux in the future to prevent this issue. However if you find an instance where the program opens its own ssh instance please let us know.
