### ISSUE TITLE
Error using PWA_GUI Gen Alpha

### ISSUE THREAD

**Issue by lmhare** [JeffersonLab/PyPWA#87]
When using Gen Alpha data in the GUI I received the following error:

`
Parsing script ... (it may take while)
<jsub><error>jlab.xmlparser.ParseException: jlab.auger.submitter.ConfiguredUserError: Missing.Track</error></jsub>
/lustre/expphy/work/hallb/clasg12/lmhare/phi/scripts/submitions/subAlpha10
`

This error followed for each of the subsequent subAlpha*\* until I stopped the process.

**Comment by Markjonestx** [comment]
Is this still an issue, or has this problem been corrected?

**Comment by Markjonestx** [comment]
Merged into #108
