### ISSUE TITLE
Not Enough Resources

### ISSUE THREAD

**Issue by lmhare** [JeffersonLab/PyPWA#90]
While running the nTrue tool on the GUI, we ran out of resources. It appears that the requested amount of memory was not sufficient to complete for a bin and we received a time out error for 1080MeV.

Is there any way to request more memory for the nTrue tool?

**Comment by Markjonestx** [comment]
nTrue, and also the rest of ISOBAR, needs a clear single unified way to adjust the resource uses for its offloaded processes.

**Comment by Markjonestx** [comment]
Merged into #108
